### ISSUE TITLE
Non-alphanumeric passwords fail for API login

### ISSUE THREAD

**Issue by moll** [Sude-/lgogdownloader#105]
I'm not sure if this is because lgogdownloader is encoding query params wrong or GOG's API is decoding them wrong, but beware that passwords with non-alphanumeric characters don't seem to work for API login. They did work on HTTP.

**Comment by moll** [comment]
Then again, this could be the fault of the older v2.26 that's in Ubuntu 16.04's repos. Is this knowlingly not a problem in the v3 branch?

**Comment by Sude-** [comment]
I haven't changed how the strings are escaped in API login requests since 2.26 (actually I haven't changed that since the initial commit) and this is the first report of this.
However I did make the downloader wait a while between API login requests because login would fail due to "429 Too Many Requests" error without the wait.

Check if you see "429 Too Many Requests" in ```lgogdownloader --login-api --verbose``` output.
If that's the case then this should be fixed in the latest version.

**Comment by moll** [comment]
I'll do so next time I'm off to download with lgogdownloader! Thanks. ;)
I'll close this until further intel to clean up your issue list.
