### ISSUE TITLE
Getting 500 Internal Server Error on attempt to download a game using cookies.

### ISSUE THREAD

**Issue by TheTharin** [Sude-/lgogdownloader#124]
I exported cookies to my cookies.txt file, but when I attempt to download any game using lgogdownloader --download --game gamename it tries 10 times and all 10 times I get 
The requested URL returned error: 500 Internal Server Error
* Closing connection 9
* Found bundle for host api.gog.com: 0x7f86e4140cb0 [can pipeline]
* Hostname api.gog.com was found in DNS cache
*   Trying 88.221.73.20...
* Connected to api.gog.com (88.221.73.20) port 80 (#10)
> GET /products/1439969610/downlink/patch/en3patch1 HTTP/1.1
Host: api.gog.com
Accept: */*
Cookie: ##**************************************************************************************

* The requested URL returned error: 500 Internal Server Error
* Closing connection 10
Getting game info 1 / 1

Though lgogdownloader --list works perfectly fine (meaning it logins with cookies). Even trying to download using lgogdownloader --download-file gogdownloader://deponia_doomsday/installer_linux_en allows to connect without prompting to login, though not working: nothing found on API:/

**Comment by TheTharin** [comment]
using --login-api allows me to connect through oauth but still 500 I S Error

**Comment by Sude-** [comment]
The recent change to using Galaxy API for most features means that exporting cookies no longer works because website login is tied with Galaxy login.
I've changed the error message when encountering reCAPTCHA during login and made some changes to Downloader::login to reflect the new behavior in edc6486

```lgogdownloader --download-file gogdownloader://deponia_doomsday/installer_linux_en``` doesn't work because "installer_linux_en" is a group id and lgogdownloader doesn't support group ids currently.
```lgogdownloader --download-file gogdownloader://deponia_doomsday/en3installer1``` should work

**Comment by TheTharin** [comment]
Great, but where did you get the "en3installer1" ID? I've tried --list-details , but only found something like that:
game-name: deponia_doomsday
game_id: *digits*
Can't be any specific, because I don't have my linux laptop at the moment.

**Comment by Sude-** [comment]
I got the file id from yepoleb's gogdb
https://gogdb.yepoleb.me/product/1439969610

If a game can't be found in gogdb for some reason but you know the product id for it you can get the details using part of the api that doesn't require authorization

    https://api.gog.com/products/{product_id}?expand=downloads,expanded_dlcs,description,screenshots,videos,related_products,changelog

For example: https://api.gog.com/products/1439969610?expand=downloads,expanded_dlcs,description,screenshots,videos,related_products,changelog

The reason it doesn't list the files is because ```galaxyAPI::installerJsonNodeToGameFileVector``` skips the file if it can't get a valid response for downlink JSON which it uses for determining the file name.
It could simply leave the file name empty and list all other details including the file id.
However Galaxy API also lists all files contained in DLCs that the user doesn't own.
Trying to get the downlink JSON for these files gives the same response code and empty response as trying to get details without valid Galaxy login tokens.
This means that ```--list-details``` would show info for irrelevant files that the user can't download which is why at least for now my solution is to just skip all files where we can't get valid downlink JSON response.

The latest git version shouldn't reach the part of code that handles listing game details before prompting to login because of missing Galaxy API tokens.
