### ISSUE TITLE
Games with incorrect titles

### ISSUE THREAD

**Issue by DoubleAgentDave** [Sude-/lgogdownloader#208]
Some games are getting listed with incorrect names e.g. "star_wars_republic_commando_copy3" is actually "Star Wars Dark Forces II", not sure if this is an issue with this program or with the GOG API.

**Comment by DoubleAgentDave** [comment]
This is evident when the --list-details option is used but the error is seen when downloading files as well. The folder name  "star_wars_republic_commando_copy3" does actually contain the executables and extras that are for "Star Wars Dark Forces II". The folder "star_wars_republic_commando" actually contains the correct executables and extras. The folder "star_wars_jedi_knight_dark_forces_ii_copy3" contains "mysteries of the sith".

I'm using the current git commit through the AUR specifically 3.8.695916a

**Comment by Sude-** [comment]
These are issues with GOG API
https://api.gog.com/products/1422286819
https://api.gog.com/products/1422285784

I don't know why GOG hasn't fixed the naming issue because I'm pretty sure someone else also had this same issue and reported the wrong naming to GOG support.
I guess I will have to report this to GOG again.

You can workaround this issue by using game specific config file

$XDG_CONFIG_HOME/lgogdownloader/gamespecific/star_wars_republic_commando_copy3.conf
```
{
    "subdir-game" : "star_wars_dark_forces_ii"
}
```

$XDG_CONFIG_HOME/lgogdownloader/gamespecific/star_wars_jedi_knight_dark_forces_ii_copy3.conf
```
{
    "subdir-game" : "star_wars_dark_forces_ii_mysteries_of_the_sith"
}
```

if $XDG_CONFIG_HOME is not set it defaults to ~/.config

**Comment by yoshimo** [comment]
So if it is an api issue, what does the official Galaxy Client when installing the game?

**Comment by Sude-** [comment]
> So if it is an api issue, what does the official Galaxy Client when installing the game?

When installing a game Galaxy uses installDirectory from build depot manifest.
Usually it is the same as title from API response with special characters stripped.
I don't know what Galaxy does when downloading offline installers because I haven't tested it.

**Comment by DoubleAgentDave** [comment]
I think, given that it's a gog API issue it probably best to close this issue, as any workaround will, hopefully, be time-limited based on the API owners solving the issue. Thanks!
