### ISSUE TITLE
Download specific game rather than search for name

### ISSUE THREAD

**Issue by inkwiwtba** [Sude-/lgogdownloader#213]
Hello,

I'm trying to download a specific game, but when I run the following command:

lgogdownloader --game army_men --no-platform-detection --language en --no-subdirectories --exclude extras,patches,languagepacks --platform win --directory ~/Downloads/19980430.army.men

the application downloads all 5 of the titles whose names include the string "army_men" in them, rather than just the first title in the series. How can I specify just the first game for my download?

Thanks in advance.

**Comment by ssokolow** [comment]
It expects a regular expression.

I use this shell function instead of invoking lgogdownloader directly:

```sh
gogd () {
        local IFS=\| 
        lgogdownloader --download --game "^($*)\$"
}
```

If I type `gogd foo_bar baz`, it runs lgogdownloader `lgogdownloader --download --game "^(foo_bar|baz)\$"`.

In your case, the important thing is to use `^army_men$` rather than `army_men`. (The `^` matches the beginning of the string and the `$` matches the end of the string, preventing it from performing a substring match on longer names.)

**Comment by inkwiwtba** [comment]
Worked perfectly. Thank you!
