### ISSUE TITLE
[ Request ] GOG Pricing ?

### ISSUE THREAD

**Issue by ekianjo** [Sude-/lgogdownloader#73]
Lgogdownloader is totally great - thanks so much for keeping this software updated. One thing I was wondering, would it be possible for you to implement some support of price checking via lgogdownloader? Is there such a way to do it via the API ?

**Comment by ssokolow** [comment]
I'm not Sude- but that really sounds out-of-scope and I seriously doubt the API exposes it, given that even Galaxy just displays that information using an embedded browser pane.

What's wrong with using IsThereAnyDeal.com for that?

**Comment by ekianjo** [comment]
Yup I kind of figured this is a little out of scope. The reason why I am interested in such a function would be for a script I am developing, so not something on the user side. Does isThereAnyDeal have such a public API then ?

**Comment by ssokolow** [comment]
Their docs are a bit [spotty](http://docs.itad.apiary.io/) but they do have APIs. I'd look to see if any of the [existing API consumers](https://isthereanydeal.com/apps/) do what you're looking for and, if not, send an e-mail to ask Tomas whether there's any possibility of getting the API extended in the near future.

**Comment by ssokolow** [comment]
Failing that, another option I'd forgotten about would be to load the [data dump](http://www.an-ovel.com/downloads/magog.txt) from [MaGOG](http://www.an-ovel.com/pages/magog.php) every day or two, since MaGOG scrapes prices from GOG.

(ITAD is the better choice though, since they have a feed of deals they check once an hour rather than walking a scraper through the catalogue as quickly as GOG will allow without blocking them.)
