### ISSUE TITLE
Delete/replace older version upon update 

### ISSUE THREAD

**Issue by murasame78** [Sude-/lgogdownloader#80]
Hi,

Don't know if that is even a possible option regarding the API, but would it make any sense to replace/delete older files with newer versions (Steam does it. It doesn't keep two versions of the same game).

I have a 200+ game collection and I usually like to run a single command to update it. But doing this I always end up with 2 (if not 3) versions of the same game on my HD and it proves a little bit annoying to check all folders one by one to make sure older versions are deleted.

Not so much of a problem when a game is a few hundreds Mb but not so great when a game is 4+ Gb.

**Comment by murasame78** [comment]
Edit.

**Comment by shakeyourbunny** [comment]
lgogdownloader is currently designed to download offline game installers (and extras), not for downloading Galaxy game file data.

**Comment by Sude-** [comment]
You can try this patch
https://sites.google.com/site/gogdownloader/delete_old_versions.diff

Using ```--download --delete-old``` makes the downloader automatically delete all installers and patches that it determines to be old versions before it starts downloading the files.
It tries to get version number from file name and then uses that to determine if the file is old version and can be deleted.
It relies on regular expression for determining the version number so changes to version string format will cause it to fail.

A warning to anyone who tries this patch:
It deletes the files automatically without user input.
Having a backup of your collection is recommended in case something goes wrong. Otherwise be prepared to download accidentally deleted files again.

**Comment by hollunder** [comment]
I have not tried the patch, but such a feature would be very welcome.

**Comment by dleslie** [comment]
Indeed, this would be a lovely feature.

**Comment by silbe** [comment]
`--check-orphan` is a good start. It only lists the files and does not remove them; you have to use `lgogdownloader --check-orphans |xargs -r rm` for that.

**Comment by kblaschke** [comment]
> you have to use `lgogdownloader --check-orphans |xargs -r rm` for that.

Just as a word of caution here, if something fails during the orphan check, lgogdownloader may spit out a list of _all_ downloaded files, which effectively deletes all downloads. Happened to me a few times, having to re-download the library.

So my advice is better redirect the output to a file, check, and if it's just a few files, pass it to `xargs rm` as above. If the list is _way_ too long, delete the file and try again. Will safe you and GOG a lot of traffic.

**Comment by Sude-** [comment]
Since 89724cd you can use ```lgogdownloader --check-orphans --delete-orphans```
