### ISSUE TITLE
DLC not downloaded (Smugglers V, Smugglers V Invasion)

### ISSUE THREAD

**Issue by hollunder** [Sude-/lgogdownloader#91]
Both games list DLCs on the game page, but those are not downloaded.
I can not find any dlc directory in my gog directory, but I tend to avoid games with DLCs, so I am not sure that other games are affected.
Am I doing something wrong or is this feature broken?

My current commandline is: "lgogdownloader --directory /mnt/gog --save-serials --platform l,w --download"
The config file contains: subdir-dlc = dlc/%dlcname%

lgogdownloader 2.28-3 (Arch Linux)

**Comment by skochneff** [comment]
I have the same issue. It was working just fine with 2.28 but stopped some time ago (no lgogdownloader updates). Now all DLC’s are marked as orphans and they aren’t displayed with `--list-details`, so it looks like some server side issue.

**Comment by icemanx7** [comment]
This is also happening with me with The Witcher 3 DLC. Does not show up using `--list-details` and is not downloading.

**Comment by Sude-** [comment]
The downloader reads the dlc count info that GOG provides and decides whether to get additional info based on the result. Sadly GOG provides incorrect DLC count info for many games and has for a long time now. I did tell GOG support about this some time ago but GOG hasn't fixed the issue yet and I'm starting to think that it probably won't be fixed anytime soon.

Try with running the downloader with ```--ignore-dlc-count```
This makes the downloader ignore all dlc count information and try to get DLC info for all games. The downside is that it makes information gathering part of the download process take significantly longer.

If ```--ignore-dlc-count``` works but you don't want it to slow down the information gathering process as much then you can use game specific config file to ignore dlc count for the specific game. For example:

~/.config/lgogdownloader/gamespecific/smugglers_v.conf
```
{
    "ignore-dlc-count": true
}
```

Or set regular expression with ignore-dlc-count
--ignore-dlc-count 'smugglers_v.*'


I think that I'll have to start maintaining a list of games that have DLC so that lgogdownloader can always ignore the dlc count info that GOG provides for games that are known to have DLC.

**Comment by icemanx7** [comment]
Thanks man it works.

**Comment by skochneff** [comment]
Thanks, `--ignore-dlc-count` works for me too.

**Comment by Sude-** [comment]
34e3af3 adds more options to ignore dlc count
[List of games that have dlc](https://github.com/Sude-/lgogdownloader-lists/blob/master/game_has_dlc.txt)  should make it so that user rarely needs to use ```--ignore-dlc-count``` as long as the list is up to date.

**Comment by hollunder** [comment]
Thanks a lot for that.
However, would it not be better to find a solution that works without manually keeping a list?
That might require talking to GOG about it.

Since we have the list now, what is the preferred way to get an update in?

**Comment by Sude-** [comment]
> However, would it not be better to find a solution that works without manually keeping a list?
> That might require talking to GOG about it.

It would be best if GOG fixed the dlc count info. I've already reported the issue to GOG support before but it hasn't been fixed. It seems to be low priority issue for them.

> Since we have the list now, what is the preferred way to get an update in?

Clone the [lgogdownloader-lists](https://github.com/Sude-/lgogdownloader-lists) repository
Add the games to ```game_has_dlc.txt``` list and create a pull request
